### ISSUE TITLE
wonlog-server options for server-host and server-port are not working

### ISSUE THREAD

**Issue by PolarLava** [Devrama/wonlog#259]
If you pass --server-host or --server-port options to the wonlog-server it's ignoring those values and continues to use the default 127.0.0.1:7978 values.  Using the browser debug in the web interface I can see it failing with a "WebSocket connection to 'ws://192.168.1.101:7978/' failed" message even when the options are passed. I installed using npm (although I would prefer docker, but that's not up to date) and in the /usr/local/lib/node_modules/wonlog/dist/wonlog/bin/wonlog-server.js file I initially change the default 127.0.0.1 to my ip, and it started to work (using the default port):

`//        .replace('%%WONLOG_RELEASE_WEBSOCKET_URL%%', `ws://${options['http-host'] || '127.0.0.1'}:${options['http-port'] || 7978}`);` 
`       .replace('%%WONLOG_RELEASE_WEBSOCKET_URL%%', `ws://${options['http-host'] || '192.168.1.101'}:${options['http-port'] || 7978}`);` 
 
After looking at it some more I realized the option names (at line 25) are incorrectly "http-host" and "http-port" instead of "server-host" and server-port" in the file.  Once I updated it with the correct option names it works fine:

`//        .replace('%%WONLOG_RELEASE_WEBSOCKET_URL%%', `ws://${options['http-host'] || '127.0.0.1'}:${options['http-port'] || 7978}`);` 
        .replace('%%WONLOG_RELEASE_WEBSOCKET_URL%%', `ws://${options['server-host'] || '127.0.0.1'}:${options['server-port'] || 7978}`);` 
`

I know you're not doing a lot of development with this recently, but I've been a long time rTail user that  got tired of the flakiness of the display not properly updating and the wrong log displaying.  Thus I'm excited at the prospects that your rewrite functions better.  Thus thank you for your time and effort!

**Comment by Devrama** [comment]
Hello, 👋
I fixed the issue with a new release, v0.2.0. `--server-host` and `--server-port`options should work correctly.
I also published a new docker image with the v0.2.0.
Thanks for the feedback. 😃
